/*
    Created by Jonas H. Melo on 2025/01/25
    This file is protected under the MIT license.

    This code is part of my studies in numerical analysis,
    following Section 5 of Chapter 2 in the book "Numerical Analysis"
    by Richard L. Burden and J. Douglas Faires, 11th edition.

    Approach:
    Let's use Steffesen's Algorithm to find the 1_st term of the sequence 
        g(x) = 1 + (sin x)^2
    {Pn} with p0 = 1
    Where P0 will be generated by Aitkens Method

    Aitken's Δ² acceleration formula is used to accelerate the convergence of the sequence:
        A_n = p_n - ((p_{n+1} - p_n)^2) / (p_{n+2} - 2*p_{n+1} + p_n)

    The sequence and the corresponding Aitken's sequence are printed step-by-step.
*/

#include<math.h>
#include<stdio.h>

double f(double x){
    return 1 + (sin(x)*sin(x));
}

int main(){
    double p0 = 1;
    double p1 = f(p0);
    double p2 = f(p1);

    int i = 1; // Nth term generated by Aitken's and Stefensen Method
    while(i <= 2){
        double p = p0 - pow((p1 - p0),2) / (p2 - 2*p1 + p0);
        printf("\n%dth P0: %.5F",i,p);
        p0 = p;
        p1 = f(p0);
        p2 = f(p1);
        i++;
    }
    return 0;
}